# Generated by Django 5.1.7 on 2025-03-28 23:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cripto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae197325-fe37-4b0a-a808-1fac38bcfed3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('559d4520-edd7-4db0-8dec-61bd26bddbb1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
