# Generated by Django 5.1.7 on 2025-04-02 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('cron', 'Cron')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d013b1a-b6f8-4e53-970b-3ba671a6f3c5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
