# Generated by Django 5.1.7 on 2025-04-03 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_user_role_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('12fa3bb8-da77-4b43-a6a8-95708cf4231b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
