# Generated by Django 5.1.7 on 2025-04-08 10:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3fca308-b219-421a-adac-a7bd5b533ba9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name', 'type')},
        ),
    ]
