# Generated by Django 5.1.7 on 2025-04-08 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_alter_income_id_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c64ddb6d-5157-4847-ad97-a2a36b3dba68'), editable=False, primary_key=True, serialize=False),
        ),
    ]
