# Generated by Django 5.1.7 on 2025-04-08 21:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('462cb6ee-2266-41d4-a06c-5074d4417296'), editable=False, primary_key=True, serialize=False),
        ),
    ]
