# Generated by Django 5.1.7 on 2025-04-08 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f6444c0-f607-423e-9912-08c7d686f7f7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
