# Generated by Django 5.1.7 on 2025-04-08 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61aec386-64fc-4479-9b1f-511936f44fbc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
