# Generated by Django 5.1.7 on 2025-04-08 22:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9183c51d-61ef-4eab-9d4d-5646d84ee46b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
