# Generated by Django 5.1.7 on 2025-04-08 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0011_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7175143-8f63-49d5-911c-ee406a5c5f49'), editable=False, primary_key=True, serialize=False),
        ),
    ]
