# Generated by Django 5.1.7 on 2025-04-08 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0012_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a41b68d1-94fe-40f4-8545-07509318cf2f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
