# Generated by Django 5.1.7 on 2025-04-08 23:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0013_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b37a95d9-9af4-4e88-9b8b-8bfbc48f893e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
