# Generated by Django 5.1.7 on 2025-04-09 08:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0014_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81fdb548-1d96-41ed-a0d0-585ad8f74d33'), editable=False, primary_key=True, serialize=False),
        ),
    ]
