# Generated by Django 5.1.7 on 2025-04-09 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0015_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e9844f7-afdc-457d-a47d-4e64d91043fa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
