# Generated by Django 5.1.7 on 2025-04-09 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0016_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14d7e5af-344b-4ab0-a860-5dac42012fff'), editable=False, primary_key=True, serialize=False),
        ),
    ]
