# Generated by Django 5.1.7 on 2025-04-09 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0017_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9dc1ed20-b944-460c-b8cd-24ffe2b9d6cd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
