# Generated by Django 5.1.7 on 2025-04-09 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0018_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01c995e0-befe-46b6-b731-ffb50bc52eeb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
