# Generated by Django 5.1.7 on 2025-04-09 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0019_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cfce752b-2be5-4467-a82f-5e63f2971619'), editable=False, primary_key=True, serialize=False),
        ),
    ]
