# Generated by Django 5.1.7 on 2025-04-09 21:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0020_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('69bc9595-6722-4f70-8e17-7970ef2895f9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
