# Generated by Django 5.1.7 on 2025-04-09 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0021_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('def52b92-2eac-44c9-8289-21a5521e0a59'), editable=False, primary_key=True, serialize=False),
        ),
    ]
