# Generated by Django 5.1.7 on 2025-04-09 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0022_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80ecc966-452a-42e4-b51a-4914cd7137b8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
