# Generated by Django 5.1.7 on 2025-04-09 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0023_alter_income_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bd6c5c9b-89b6-42a9-844c-558a373286de'), editable=False, primary_key=True, serialize=False),
        ),
    ]
