# Generated by Django 5.1.7 on 2025-04-09 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0026_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6eeb366e-049a-4b1d-b4c8-23fec5f31c19'), editable=False, primary_key=True, serialize=False),
        ),
    ]
