# Generated by Django 5.1.7 on 2025-04-10 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0028_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c1224a6-69da-4f22-a629-67b5963f13f7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
