# Generated by Django 5.1.7 on 2025-04-10 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0029_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e815f6d-0831-43cb-861b-23ca26659bc2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
