# Generated by Django 5.1.7 on 2025-04-10 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0030_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43c45263-d17b-4a39-b64c-001d51136d9d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
