# Generated by Django 5.1.7 on 2025-04-10 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0031_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e180f78d-b32b-407a-9946-ba40deaee8be'), editable=False, primary_key=True, serialize=False),
        ),
    ]
