# Generated by Django 5.1.7 on 2025-04-11 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0032_alter_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.UUID('703ac504-5012-4b12-a12f-a372f546c60b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
