# Generated by Django 5.1.7 on 2025-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0033_alter_income_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='title',
            field=models.CharField(default='Meta sin título', max_length=100),
            preserve_default=False,
        ),
    ]
