# Generated by Django 5.1.7 on 2025-04-18 11:22

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0036_monthlyplan'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE savings_monthlyplan ALTER COLUMN reflection DROP NOT NULL;",
            reverse_sql="ALTER TABLE savings_monthlyplan ALTER COLUMN reflection SET NOT NULL;"
        )
    ]