# Generated by Django 5.1.7 on 2025-04-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0037_make_reflection_nullable'),
        ('savings', '0038_clean_invalid_reflections'),
    ]

    operations = [
    ]
