# Generated by Django 5.1.7 on 2025-04-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0039_merge_20250418_1125'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE savings_monthlyplan
            SET reflection = NULL
            WHERE NOT reflection ~* '^[0-9a-fA-F-]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$';
            """,
            reverse_sql=migrations.RunSQL.noop
        )
    ]
