# Generated by Django 5.1.7 on 2025-04-18 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0040_clean_invalid_reflection_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyplan',
            name='reflection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_plan', to='savings.reflection'),
        ),
    ]
