# Generated by Django 5.1.7 on 2025-04-18 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0042_insert_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyplan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
