# Generated by Django 5.1.7 on 2025-04-19 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0043_alter_monthlyplan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reflection',
            name='monthly_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_monthly_plan', to='savings.monthlyplan'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='reflection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plan_reflection', to='savings.reflection'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
